language: cpp

matrix:
  include:
    #Linux - Emscripten
    - os: linux
      env:
        - BUILD_CONFIG=dist
        - COMPILER=emcc
        - COVERAGE=false
    # Windows:
    - os: windows
      env:
        - BUILD_CONFIG=debug
        - COMPILER=msvc
        - COVERAGE=false
    - os: windows
      env:
        - BUILD_CONFIG=release
        - COMPILER=msvc
        - COVERAGE=false
    - os: windows
      env:
        - BUILD_CONFIG=dist
        - COMPILER=msvc
        - COVERAGE=false
    # Desktop Linux:
    #Linux - GCC
    - os: linux
      env:
        - BUILD_CONFIG=debug
        - COMPILER=gcc
        - COVERAGE=true
    - os: linux
      env:
        - BUILD_CONFIG=release
        - COMPILER=gcc
        - COVERAGE=false
    - os: linux
      env:
        - BUILD_CONFIG=dist
        - COMPILER=gcc
        - COVERAGE=false
    #Linux - Clang
    - os: linux
      env:
        - BUILD_CONFIG=debug
        - COMPILER=clang
        - COVERAGE=false
    - os: linux
      env:
        - BUILD_CONFIG=release
        - COMPILER=clang
        - COVERAGE=false
    - os: linux
      env:
        - BUILD_CONFIG=dist
        - COMPILER=clang
        - COVERAGE=false


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]
    then
      wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz -O premake.tar.gz
      tar -xf premake.tar.gz
      chmod +x premake5
      export PATH=$PATH:$(pwd)
      gcc -v && g++ -v --version
    fi
  - |
    if [ $COMPILER == "emcc" ]
    then
      wget -q https://github.com/emscripten-core/emsdk/archive/master.tar.gz
      tar -xvf master.tar.gz
      emsdk-master/emsdk update
      emsdk-master/emsdk install latest-fastcomp
      emsdk-master/emsdk activate latest-fastcomp
    fi

script:
  - python .github/CI/build.py $TRAVIS_OS_NAME $COMPILER $BUILD_CONFIG $COVERAGE
