language: cpp

matrix:
  include:
    #Linux - Emscripten
    - os: linux
      env:
        - BUILD_CONFIG=release
        - COMPILER=emcc
        - COVERAGE=false
    # Windows:
    - os: windows
      env:
        - BUILD_CONFIG=debug
        - COMPILER=msvc
        - COVERAGE=false
    - os: windows
      env:
        - BUILD_CONFIG=release
        - COMPILER=msvc
        - COVERAGE=false
    # Desktop Linux:
    #Linux - GCC
    - os: linux
      env:
        - BUILD_CONFIG=debug
        - COMPILER=gcc
        - COVERAGE=true
    - os: linux
      env:
        - BUILD_CONFIG=release
        - COMPILER=gcc
        - COVERAGE=false
    #Linux - Clang
    - os: linux
      env:
        - BUILD_CONFIG=debug
        - COMPILER=clang
        - COVERAGE=false
    - os: linux
      env:
        - BUILD_CONFIG=release
        - COMPILER=clang
        - COVERAGE=false


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - tree

install:
  - |
    if [ $COMPILER == "emcc" ]
    then
      wget -q https://github.com/emscripten-core/emsdk/archive/master.tar.gz
      tar -xvf master.tar.gz
      emsdk-master/emsdk update
      emsdk-master/emsdk install latest-fastcomp
      emsdk-master/emsdk activate latest-fastcomp
    fi

script:
  - python .github/CI/build.py $TRAVIS_OS_NAME $COMPILER $BUILD_CONFIG $COVERAGE
